#!/proj/csc671/proj_shared/dc-install/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from datacrumbs.main import build
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(build())
