#ifndef DATACRUMBS_SERVER_BPF_COMMON_H
#define DATACRUMBS_SERVER_BPF_COMMON_H
// Generated by DataCrumbs during system build
#include <datacrumbs/server/bpf/vmlinux.h>
//
#include <bpf/bpf_core_read.h>
//
#include <bpf/bpf_helpers.h>
//
#include <bpf/bpf_tracing.h>
//
#include <bpf/usdt.bpf.h>
//

// Common definitions for BPF programs
#include <datacrumbs/server/bpf/macros.bpf.h>
#include <datacrumbs/server/bpf/shared.h>

DATACRUMBS_MAP(pid_map, u32, u64, 1024);
DATACRUMBS_MAP(fn_pid_map, struct fn_key_t, struct fn_value_t);
DATACRUMBS_RINGBUF(output, 1024 * 1024 * 16U);  // 16MB ring buffer

#ifndef DATACRUMBS_TRACE_ALL
#define DATACRUMBS_TRACE_ALL 0
#endif

#if defined(DATACRUMBS_TRACE_ALL) && (DATACRUMBS_TRACE_ALL == 1)
static inline __attribute__((always_inline)) int need_tracing(struct fn_key_t* key, u64* start_ts) {
  key->id = bpf_get_current_pid_tgid();
  return 1;
}
#else
static inline __attribute__((always_inline)) int need_tracing(struct fn_key_t* key, u64* start_ts) {
  key->id = bpf_get_current_pid_tgid();
  u32 pid = key->id & 0xFFFFFFFF;
  (void)pid;
  start_ts = (u64*)bpf_map_lookup_elem(&pid_map, &pid);
  if (start_ts == 0 || key->id == 0) return 0;
  return 1;
}
#endif

#ifndef DATACRUMBS_TRACING_ENABLE
#define DATACRUMBS_TRACING_ENABLE 1
#endif

#if defined(DATACRUMBS_TRACING_ENABLE) && (DATACRUMBS_TRACING_ENABLE == 1)
static inline __attribute__((always_inline)) int generic_entry(struct pt_regs* ctx, u64 event_id) {
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  struct fn_value_t fn = {};
  fn.ts = bpf_ktime_get_ns();
  bpf_map_update_elem(&fn_pid_map, &key, &fn, BPF_ANY);
  DBG_PRINTK("Pushed pid:%d, event_id:%llu to map\n", (u32)key.id, event_id);
  return 0;
}
#else
static inline __attribute__((always_inline)) int generic_entry(struct pt_regs* ctx, u64 event_id) {
  return 0;
}
#endif
#if defined(DATACRUMBS_TRACING_ENABLE) && (DATACRUMBS_TRACING_ENABLE == 1)
static inline __attribute__((always_inline)) int generic_exit(struct pt_regs* ctx, u64 event_id) {
  u64 te = bpf_ktime_get_ns();
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  struct fn_value_t* fn = bpf_map_lookup_elem(&fn_pid_map, &key);
  if (fn == 0) return 0;  // missed entry
  DATACRUMBS_SKIP_SMALL_EVENTS(fn, te);
  struct general_event_t* event;
  DATACRUMBS_RB_RESERVE(output, struct general_event_t, event);
  event->type = 1;
  event->id = key.id;
  event->event_id = event_id;
  DATACRUMBS_COLLECT_TIME(event);
  DATACRUMBS_EVENT_SUBMIT(event);
  return 0;
}
#else
static inline __attribute__((always_inline)) int generic_exit(struct pt_regs* ctx, u64 event_id) {
  return 0;
}
#endif

#if defined(DATACRUMBS_TRACING_ENABLE) && (DATACRUMBS_TRACING_ENABLE == 1)
static inline __attribute__((always_inline)) int usdt_entry(struct pt_regs* ctx, u64 event_id) {
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  struct fn_value_t fn = {};
  fn.ts = bpf_ktime_get_ns();
  bpf_map_update_elem(&fn_pid_map, &key, &fn, BPF_ANY);
  DBG_PRINTK("USDT  Pushed pid:%d, event_id:%llu to map\n", (u32)key.id, event_id);
  return 0;
}

#else
static inline __attribute__((always_inline)) int usdt_entry(struct pt_regs* ctx, u64 event_id) {
  return 0;
}
#endif

#if defined(DATACRUMBS_TRACING_ENABLE) && (DATACRUMBS_TRACING_ENABLE == 1)
static inline __attribute__((always_inline)) void extract_filename(const char* fqname, int fq_size,
                                                                   char* fname, int fname_size) {
  int target_dot = 2;
  int dot_count = 0;
  int dot = 0;
  // Scan backwards for the last and second last '.'
  for (int i = fq_size - 1; i >= 0 && fq_size - i < fname_size; --i) {
    if (fqname[i] == '.' || fqname[i] == '/') {
      dot_count++;
      if (dot_count == target_dot) {
        dot = i + 1;
        break;
      }
    }
  }
  int start = dot;
  int j = 0;
  int limit = fname_size - 1;
  // Copy from after the last '.' to the output buffer, within fname_size
  for (; start < fq_size - 1 && fqname[start] != '\0' && j < limit; ++start, ++j) {
    fname[j] = fqname[start];
  }
  fname[j] = '\0';
}
static inline __attribute__((always_inline)) int usdt_exit(struct pt_regs* ctx, u64 event_id,
                                                           long clazz, long method) {
  u64 te = bpf_ktime_get_ns();
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  struct fn_value_t* fn = bpf_map_lookup_elem(&fn_pid_map, &key);
  if (fn == 0) return 0;  // missed entry
  DATACRUMBS_SKIP_SMALL_EVENTS(fn, te);
  struct usdt_event_t* event;
  DATACRUMBS_RB_RESERVE(output, struct usdt_event_t, event);
  event->type = 3;
  event->id = key.id;
  event->event_id = event_id;
  DATACRUMBS_COLLECT_TIME(event);

  char local_clazz[MAX_CLASS_READ_LEN];                                                // 100
  long len = bpf_probe_read_user_str(&local_clazz, MAX_CLASS_READ_LEN, (void*)clazz);  // 90
  if (len < 0) {
    local_clazz[0] = '\0';  // Fallback to empty string on error
  } else {
    int contains_bootstrap = 0;
    if (len > MAX_CLASS_LEN) {
      long offset = len - MAX_CLASS_LEN;  // Ensure we don't overflow 90 - 80 = 10
      for (int i = 0; i < MAX_CLASS_LEN && i + offset < len; ++i) {
        if (local_clazz[i + offset] == '>') {
          contains_bootstrap = 1;
          break;
        }
        event->clazz[i] = local_clazz[i + offset];
      }
    } else {
      for (int i = 0; i < len; ++i) {
        if (local_clazz[i] == '>') {
          contains_bootstrap = 1;
          break;
        }
        event->clazz[i] = local_clazz[i];
      }
      if (contains_bootstrap) {
        bpf_ringbuf_discard(event, 0);
        return 0;  // Discard event if it contains '>'
      }
      // bpf_probe_read_str(&event->clazz, len, (void*)local_clazz);
    }
  }
  // extract_filename(local_clazz, sizeof(local_clazz), event->clazz, MAX_STRING_LENGTH);
  bpf_probe_read_user(&event->method, sizeof(event->method), (void*)method);
  DATACRUMBS_EVENT_SUBMIT(event);
  return 0;
}

#else
static inline __attribute__((always_inline)) int usdt_exit(struct pt_regs* ctx, u64 event_id,
                                                           long clazz, long method) {
  return 0;
}
#endif
char LICENSE[] SEC("license") = "Dual BSD/GPL";
#endif  // DATACRUMBS_SERVER_BPF_COMMON_H