#ifndef DATACRUMBS_SERVER_BPF_COMMON_H
#define DATACRUMBS_SERVER_BPF_COMMON_H
// Generated by DataCrumbs during system build
#include <datacrumbs/server/bpf/vmlinux.h>
//
#include <bpf/bpf_core_read.h>
//
#include <bpf/bpf_helpers.h>
//
#include <bpf/bpf_tracing.h>
//
#include <bpf/usdt.bpf.h>
//

// Common definitions for BPF programs
#include <datacrumbs/server/bpf/macros.bpf.h>
#include <datacrumbs/server/bpf/shared.h>

DATACRUMBS_MAP(pid_map, u64, u64, 1024);
DATACRUMBS_MAP(fn_pid_map, struct fn_key_t, struct fn_value_t);
DATACRUMBS_RINGBUF(output, 1 << 16);

static inline __attribute__((always_inline)) int need_tracing(struct fn_key_t* key, u64* start_ts) {
  key->id = bpf_get_current_pid_tgid();
  u32 pid = key->id;
  (void)pid;
  start_ts = (u64*)bpf_map_lookup_elem(&pid_map, &key->id);
  if (start_ts == 0 || key->id == 0) return 0;
  return 1;
}

static inline __attribute__((always_inline)) int generic_entry(struct pt_regs* ctx, u64 event_id) {
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  struct fn_value_t fn = {};
  fn.ts = bpf_ktime_get_ns();
  bpf_map_update_elem(&fn_pid_map, &key, &fn, BPF_ANY);
  DBG_PRINTK("Pushed pid:%d, event_id:%llu to map\n", (u32)key.id, event_id);
  return 0;
}
static inline __attribute__((always_inline)) int generic_exit(struct pt_regs* ctx, u64 event_id) {
  u64 te = bpf_ktime_get_ns();
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  struct fn_value_t* fn = bpf_map_lookup_elem(&fn_pid_map, &key);
  if (fn == 0) return 0;  // missed entry
  struct general_event_t* event;
  DATACRUMBS_RB_RESERVE(output, struct general_event_t, event);
  event->type = 1;
  event->id = key.id;
  event->event_id = event_id;
  DATACRUMBS_COLLECT_TIME(event);
  DATACRUMBS_SKIP_SMALL_EVENTS(event);
  bpf_ringbuf_submit(event, 0);
  DBG_PRINTK("Pushed pid:%d, event_id:%llu to output\n", (u32)key.id, event_id);
  return 0;
}

static inline __attribute__((always_inline)) int usdt_entry(struct pt_regs* ctx, u64 event_id) {
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  struct fn_value_t fn = {};
  fn.ts = bpf_ktime_get_ns();
  bpf_map_update_elem(&fn_pid_map, &key, &fn, BPF_ANY);
  DBG_PRINTK("USDT  Pushed pid:%d, event_id:%llu to map\n", (u32)key.id, event_id);
  return 0;
}
static inline __attribute__((always_inline)) int usdt_exit(struct pt_regs* ctx, u64 event_id,
                                                           long clazz, long method) {
  u64 te = bpf_ktime_get_ns();
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  struct fn_value_t* fn = bpf_map_lookup_elem(&fn_pid_map, &key);
  if (fn == 0) {
    DBG_PRINTK("USDT Exit Missed Entry called event_id:%llu pid:%d\n", event_id, (u32)key.id);
    return 0;  // missed entry
  }
  struct usdt_event_t* event;
  DATACRUMBS_RB_RESERVE(output, struct usdt_event_t, event);
  event->type = 3;
  event->id = key.id;
  event->event_id = event_id;
  DATACRUMBS_COLLECT_TIME(event);
  DATACRUMBS_SKIP_SMALL_EVENTS(event);
  bpf_probe_read_user(&event->clazz, sizeof(event->clazz), (void*)clazz);
  bpf_probe_read_user(&event->method, sizeof(event->method), (void*)method);
  bpf_ringbuf_submit(event, 0);
  // bpf_ringbuf_output(&output, &event, sizeof(event), 0);
  DBG_PRINTK("USDT Pushed pid:%d, event_id:%llu to %s.%s output\n", (u32)key.id, event_id,
             event->clazz, event->method);
  return 0;
}

static inline __attribute__((always_inline)) u64 get_hash(unsigned char* str, u64 len) {
  u64 hash = 5381;
  int c = *str;
  int count = 0;
  while (count < len && c) {
    hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
    c = *str++;
    count++;
  }
  return hash;
}

char LICENSE[] SEC("license") = "Dual BSD/GPL";
#endif  // DATACRUMBS_SERVER_BPF_COMMON_H