name: chameleon
install_dir: /home/${USER}/datacrumbs/install
# mode options: `trace` or `profile`
# currently only `trace` mode
mode: trace
file: /home/${USER}/logs/chameleon-trace.pfw
# if no headers installed use regex as sys.*
system:
  - name: ext4
    regex: ext4.*
io:
  - name: libc
    link: /usr/lib/x86_64-linux-gnu/libc.so.6
  - name: hdf5
    link: /home/${USER}/datacrumbs/install/lib/libhdf5.so
user:
  - name: test_posix
    link: /home/${USER}/datacrumbs/install/libexec/datacrumbs/bin/df_tracer_test
    regex: ^(?!__).*
profile:
  interval_sec: 0.0001

trace:
  args: 1
  # options: `ring_buffer` or `perf`
  type: ring_buffer
