name: lima
install_dir: /home/lima.linux/datacrumbs/install
mode: trace
file: /home/lima.linux/logs/traceH5D.pfw
# system:
#   - name: sys
#     header: /usr/src/linux-headers-5.15.0-143/include/linux/syscalls.h
io:
  # - name: libc
  #   link: /usr/lib/x86_64-linux-gnu/libc.so.6
  - name: hdf5
    link: /home/lima.linux/apps/hdf5/lib/libhdf5.so
    regex: H5D.*
  # - name: h5d
  #   link: /home/lima.linux/apps/hdf5/lib/libhdf5.so
  #   regex: H5D.*
  # - name: h5f
  #   link: /home/lima.linux/apps/hdf5/lib/libhdf5.so
  #   regex: H5F.*
user:
  - name: h5bench
    link: /home/lima.linux/apps/simple_tests/create_hdf5_c
    regex: ^(?!__).*
profile:
  interval_sec: 0.0001

trace:
  args: 1
  type: ring_buffer # ring_buffer
