name: wombat
install_dir: /proj/csc671/proj_shared/datacrumbs/install
mode: trace
file: logs/wombat-trace.pfw
user:
  - name: ior
    link: /proj/csc671/proj_shared/datacrumbs/install/bin/ior
    regex: .*
  - name: mpi
    link: /autofs/nccs-svm1_wombat_sw/RHEL9.4/spack/opt/spack/linux-rhel9-neoverse_n1/gcc-13.2.0/openmpi-5.0.5-4sftj52a3kir2t6d63yb3ywzoph6xsfw/lib/libmpi.so
    regex: ^PMPI.*
  - name: hdf5
    link: /proj/csc671/proj_shared/datacrumbs/install/lib/libhdf5.so
    regex: ^H5.*
profile:
  interval_sec: 0.0001

trace:
  args: 1
  type: ring_buffer # ring_buffer