name: lead2
install_dir: /home/haridev/datacrumbs/install
mode: tracer
trace_file_path: /scratch/haridev/logs/lead2-trace.pfw
capture_probes:
  - name: sys
    probe: syscalls
    type: header
    file: /usr/src/kernels/5.14.0-570.18.1.1toss.t5.x86_64/include/linux/syscalls.h
    regex: sys_.*
profiling_interval: 0.0001