name: ebpf
mode: tracer
trace_file_path: /scratch/haridev/logs/lead2-trace.pfw
capture_probes:
  - name: sys
    probe: syscalls
    type: header
    file: /usr/src/linux-hwe-6.5-headers-6.5.0-44/include/linux/syscalls.h
    regex: sys_.*
profiling_interval: 0.0001