name: ares
install_dir: /home/xcatcadmin/datacrumbs/install
# mode can be "trace" or "profile" (rn only trace works)
mode: trace
file: /home/xcatcadmin/logs/ares-trace.pfw
io:
  - name: iowarp
    link: /mnt/common/nrajesh/spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-11.4.0/iowarp-runtime-main-qm7xufwllxq47axtogsdklo4kliy3tkn/lib/libchimaera_remote_queue.so
    regex: .*
profile:
  interval_sec: 0.0001

trace:
  args: 1
    # ring_buffer or perf
  type: ring_buffer