name: lead2
install_dir: /home/haridev/datacrumbs/install
mode: tracer
trace_file_path: /scratch/haridev/logs/lead2-trace.pfw
capture_probes:
  - name: sys
    probe: syscalls
    type: header
    file: /usr/src/kernels/5.14.0-570.18.1.1toss.t5.x86_64/include/linux/syscalls.h
    regex: sys_.*
  - name: libc
    probe: uprobe
    type: binary
    file: /usr/lib64/libc.so.6
  - name: bio
    probe: kprobe
    type: ksym
    regex: bio.*
  - name: python
    probe: usdt
    type: usdt
    binary_path: /lib64/libpython3.9.so.1.0
    provider: python
profiling_interval: 0.0001